version: "3.8"
services:
  warp-clash:
    build: .
    ports:
      - "21001:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env.local
    volumes:
      - ./config:/app/config
      - ./account:/app/account
      - ./logs:/app/logs